# Generated by Django 3.1.4 on 2022-01-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
